# https://github.com/ianyh/Amethyst/blob/development/.amethyst.sample.yml
# https://github.com/ianyh/Amethyst/blob/development/Amethyst/default.amethyst
layouts:
  - tall
  - fullscreen
  # - tall-right
  - wide
  # - two-pane
  # - middle-wide
  # - 3column-left
  # - 3column-middle
  # - 3column-right
  # - 4column-left
  # - 4column-right
  - column
  # - row
  # - floating
  # - widescreen-tall
  # - widescreen-tall-right
  # - bsp
