{
  lib,
  rustPlatform,
  fetchFromGitHub,
  stdenv,
  darwin,
}:
rustPlatform.buildRustPackage rec {
  pname = "uv-migrator";
  version = "2025.5.0";

  src = fetchFromGitHub {
    owner = "stvnksslr";
    repo = "uv-migrator";
    rev = "v${version}";
    hash = "sha256-iHBEC8vVZfHg5ZhOvTveGXSMNKuq1K/5Hy1j0AVk/Yo=";
  };

  cargoHash = "sha256-yBJTzUnplERrZ5mv/ycqgmKo+H0Myr2vPVAa6enfmcY=";

  # generated by nix-init but not needed
  # buildInputs = lib.optionals stdenv.isDarwin [
  #   darwin.apple_sdk.frameworks.Security
  # ];

  meta = {
    description = "Tool for migrating to the uv package manager";
    homepage = "https://github.com/stvnksslr/uv-migrator";
    changelog = "https://github.com/stvnksslr/uv-migrator/blob/${src.rev}/CHANGELOG.md";
    license = lib.licenses.mpl20;
    maintainers = with lib.maintainers; [ mirkolenz ];
    mainProgram = "uv-migrator";
  };
}
