{ lib, pkgs, extras, config, ... }:
let
  inherit (extras) unstable;
in
{
  imports = [
    ./homebrew.nix
    ./settings.nix
  ];

  environment.loginShell = pkgs.fish;
  services.nix-daemon.enable = true;
  # TODO: Document that this content shall be copied from `/etc/nix/nix.conf` after running the nix-installer
  nix.extraOptions = ''
    # Generated by https://github.com/DeterminateSystems/nix-installer, version 0.5.0.
    bash-prompt-prefix = (nix:$name)\040
    extra-nix-path = nixpkgs=flake:nixpkgs
    auto-optimise-store = true
    build-users-group = nixbld
    experimental-features = nix-command flakes
  '';
}
