name: checks
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# keep job names in sync: https://github.com/mirkolenz/nixos/settings/rules/3352950
jobs:
  matrix:
    name: build.${{ matrix.system }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://docs.github.com/en/actions/reference/runners/github-hosted-runners
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
          - system: x86_64-linux
            runner: ubuntu-24.04
          - system: aarch64-darwin
            runner: macos-26
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@v10
        if: runner.os == 'Linux'
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            accept-flake-config = true
            keep-going = true
            download-buffer-size = 1000000000
            log-lines = 200
      - uses: cachix/cachix-action@v16
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix flake check --show-trace
  checks:
    needs: matrix
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Check matrix results
        run: |
          result="${{ needs.matrix.result }}"
          if [[ $result == "success" ]]; then
            exit 0
          else
            exit 1
          fi
