on:
  push:
    branches: [main]
  pull_request:
jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: cachix/cachix-action@v14
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check --show-trace
  build:
    if: ${{ github.event_name == 'push' }}
    needs: check
    uses: ./.github/workflows/build.yaml
