on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin
    permissions:
      contents: read
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix flake check --system ${{ matrix.system }} --show-trace
