on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: nixbuild/nixbuild-action@v20
        with:
          nixbuild_token: ${{ secrets.nixbuild_token }}
          generate_summary_for: job
      - name: nix flake check
        run: |
          nix flake check \
            --print-build-logs \
            --show-trace \
            --builders "" \
            --max-jobs 2 \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net
