on:
  push:
    branches:
      - main
  pull_request:
jobs:
  matrix:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.generate.outputs.build-matrix }}
      eval: ${{ steps.generate.outputs.eval-matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - id: generate
        name: Generate Matrix
        run: |
          set -Eeu
          echo "build-matrix=$(nix eval --json '.#githubActionsBuild.matrix')" >> "$GITHUB_OUTPUT"
          echo "eval-matrix=$(nix eval --json '.#githubActionsEval.matrix')" >> "$GITHUB_OUTPUT"

  build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.matrix.outputs.build)}}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: nix build
        run: |
          nix build \
            --print-build-logs \
            --show-trace \
            '.#${{ matrix.attr }}'

  eval:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.matrix.outputs.eval)}}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: nix eval
        run: |
          nix eval \
            --print-build-logs \
            --show-trace \
            '.#${{ matrix.attr }}'
