on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: nix flake check
        run: |
          nix flake check \
            --print-build-logs \
            --show-trace
