# https://github.com/DeterminateSystems/update-flake-lock/blob/main/update-flake-lock.sh

on:
  push: ~
  workflow_dispatch: ~
  schedule:
    - cron: "0 23 * * *" # every day at 23:00 UTC
jobs:
  update_flake_lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v2
      - run: "nix flake update --commit-lock-file --commit-lockfile-summary 'chore(deps): update flake.lock'"
      - run: "git push"
