# https://github.com/DeterminateSystems/update-flake-lock/blob/main/update-flake-lock.sh
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  # push: ~
  workflow_dispatch: ~
  schedule:
    - cron: "0 1 * * *" # every day at 1am UTC(!)
jobs:
  lock-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: fregante/setup-git-user@v2
      - uses: DeterminateSystems/nix-installer-action@v4
      - run: "nix flake update --commit-lock-file --commit-lockfile-summary 'chore(deps): update flake.lock'"
      - run: "git push"
