on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # every day at 1am UTC(!)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          extra-conf: |
            accept-flake-config = true
      - name: nix flake update
        run: |
          nix flake update \
            --commit-lock-file \
            --commit-lock-file-summary "chore(deps): update flake.lock"
      - name: nix run .#updater
        run: |
          nix run .#updater
          git commit -m "chore(deps): update packages" overlays || true
      - uses: peter-evans/create-pull-request@6
        id: pr
        with:
          pr-title: "chore(deps): auto-update"
          token: ${{ steps.generate-token.outputs.token }}
          branch: update-deps
          delete-branch: true
      - name: automerge
        run: gh pr merge --auto --rebase ${{ steps.pr.outputs.pull-request-number }}
        if: steps.pr.outputs.pull-request-number != ''
        env:
          # if using a personal access token, workflows are run twice
          # first in the pr and then after merging
          GITHUB_TOKEN: ${{ github.token }}
