on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # every day at 1am UTC(!)
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: DeterminateSystems/update-flake-lock@v24
        id: update
        with:
          commit-msg: "chore(deps): update flake.lock"
          pr-title: "chore(deps): update flake.lock"
          token: ${{ secrets.GH_TOKEN }}
      - name: automerge
        run: gh pr merge --auto --rebase ${{ steps.update.outputs.pull-request-number }}
        if: steps.update.outputs.pull-request-number != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
