on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # every day at 1am UTC(!)
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      ref: ${{ steps.ref.outputs.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: cachix/cachix-action@v15
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
        name: Run git config
      - run: |
          nix flake update \
            --commit-lock-file \
            --commit-lockfile-summary "chore(deps): update flake.lock"
        name: Run nix flake update
      - run: nix flake check --show-trace
      - run: git push
      - run: echo "ref=$(git rev-parse HEAD )" >> "$GITHUB_OUTPUT"
        id: ref
        name: Set ref output
  build:
    needs: update
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{ needs.update.outputs.ref }}
