on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # every day at 1am UTC(!)
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: nix flake update
        run: |
          nix flake update \
            --commit-lock-file \
            --commit-lock-file-summary "chore(deps): update flake.lock"
      - name: nix flake check
        run: |
          nix flake check \
            --print-build-logs \
            --show-trace
      - name: git config and push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git push
