on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # every day at 1am UTC(!)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/update-flake-lock@v25
        id: update
        with:
          commit-msg: "chore(deps): update flake.lock"
          pr-title: "chore(deps): update flake.lock"
          token: ${{ steps.generate-token.outputs.token }}
      - name: automerge
        run: gh pr merge --auto --rebase ${{ steps.update.outputs.pull-request-number }}
        if: steps.update.outputs.pull-request-number != ''
        env:
          # if using a personal access token, workflows are run twice
          # first in the pr and then after merging
          GITHUB_TOKEN: ${{ github.token }}
